project:
  type: website 

website:
  page-navigation: true
  title: "PyCologne"
  site-url: "https://pycologne-group.github.io/community-organisation"
  repo-url: "https://github.com/pycologne-group/community-organisation"
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; 2024 PyCologne. All Rights Reserved."
  
  sidebar:
    logo: "images/logo.svg.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/pycologne-group
        text: "PyCologne GitHub Organisation"
      - icon: meetup
        href: https://www.meetup.com/pycologne
        text: "PyCologne Meetup Group" 
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto
